In [ ]:
#!pip install yfinance

# Invest Portfolio

Ivan has a large amout of money, and he starts to think how to invest this money to gain maximum profit.
He chooses 10 candidate companies for that, but since Ivan is new in investing he needs your advice. In this notebook we will help Ivan in his journey.      

In [1]:
# 10 companies to consider, key - ticker name, value -  short description.
tickers = {
     "BA": "The Boeing Company",
     "MCD": "McDonald's Corporation",
     "GOOGL": "Google Company",
     "DIS": "The Walt Disney Company",
     "PFE": "Pfizer Inc.",
     "AMT": "American Tower Corporation",
     "VOD": "Vodafone Group Public Limited Company",
     "BNP.PA": "BNP Paribas Bank",
     "ADS.DE": "Adidas",
     "TM": "Toyota Motor Corporation",
 }


## Task 1 Download and preprocess data

We will use data from 2010 till 2021 for training and data from 2021 till 2024  for testing purpose.



In [61]:
start_train_date = "2010-01-01"
end_train_date = "2021-01-01"
start_test_date = "2021-01-01"
end_test_date = "2024-01-01"

Write a function that takes ticker name, start and end dates and returns pandas series of annual stock prices.



In [91]:
import yfinance as yf
import pandas as pd
import numpy as np


def download_annual_stock_prices(tickers_list, buy_date= "2010-01-01", sell_date="2021-01-01"):
    """Download the annual stock price using yf.download"""
    return yf.download(tickers_list, start=buy_date, end=sell_date, interval="1mo", progress=False)["Open"][::12]

In [92]:
annual_stock_price_df = download_annual_stock_prices(list(tickers), start_train_date, end_train_date)
test_annual_stock_price_df = download_annual_stock_prices(list(tickers), start_test_date, end_test_date)

In [93]:
test_annual_stock_price_df

Ticker          ADS.DE         AMT          BA     BNP.PA         DIS  \
Date                                                                    
2021-01-01  297.899994  226.070007  210.000000  43.105000  182.259995   
2022-01-01  254.350006  292.369995  204.000000  61.110001  155.830002   
2023-01-01  128.339996  214.000000  192.949997  53.910000   88.980003   

Ticker           GOOGL         MCD        PFE          TM        VOD  
Date                                                                  
2021-01-01   88.000000  214.490005  36.869999  155.809998  17.040001  
2022-01-01  145.054993  269.489990  58.500000  186.809998  15.200000  
2023-01-01   89.589996  263.529999  51.009998  137.960007  10.290000

In [94]:
annual_stock_price_df

Ticker          ADS.DE         AMT          BA     BNP.PA         DIS  \
Date                                                                    
2010-01-01   37.770000   43.490002   55.720001  55.900002   32.500000   
2011-01-01   49.279999   51.910000   66.150002  48.299999   37.740002   
2012-01-01   49.509998   60.450001   74.699997  30.450001   37.970001   
2013-01-01   67.330002   78.389999   76.550003  42.584999   50.799999   
2014-01-01   92.639999   79.510002  136.009995  56.650002   76.040001   
2015-01-01   57.619999   99.160004  131.070007  49.259998   94.910004   
2016-01-01   89.910004   96.290001  141.380005  52.590000  103.120003   
2017-01-01  149.750000  106.730003  156.300003  60.119999  105.300003   
2018-01-01  167.149994  143.160004  295.750000  62.250000  108.949997   
2019-01-01  182.399994  157.110001  316.190002  39.474998  108.099998   
2020-01-01  289.799988  229.679993  328.549988  52.830002  145.289993   

Ticker          GOOGL         MCD        PFE          TM        VOD  
Date                                                                 
2010-01-01  15.689439   62.630001  17.333965   84.750000  23.649338  
2011-01-01  14.926927   77.099998  16.793169   79.019997  26.941896  
2012-01-01  16.339840  101.330002  20.740038   67.389999  28.695210  
2013-01-01  18.003504   89.400002  24.222012   94.779999  26.258919  
2014-01-01  27.914413   96.809998  28.908918  121.599998  39.755352  
2015-01-01  26.629999   94.129997  29.667933  126.230003  34.080002  
2016-01-01  38.110001  117.250000  30.218216  121.519997  32.119999  
2017-01-01  40.030998  121.860001  31.024668  118.169998  24.840000  
2018-01-01  52.651001  173.729996  34.516129  127.430000  32.160000  
2019-01-01  51.360001  175.410004  40.910816  114.680000  19.299999  
2020-01-01  67.420502  198.000000  37.286530  142.000000  19.379999


Let's define $\xi_i$ as random variable equals annual return ratio of the $\text{stock}_i$  relative to the buying price.

Convert annual stock price to annual return ratio considering that we've bought stock at moment $t=0$.
i.e. if the annoaul stock prices are $(10, 15, 12, 13)$,
 annual return ratio will be $(0.5, -0.3, 0.1)$

In [95]:
def get_annual_return_ratio_from_initial(prices_df):
    diff_df = prices_df.diff(1).dropna()
    return diff_df.div(prices_df.iloc[0])


test_stock_price_df = pd.DataFrame({
    "ticker_1": [1, 3, 2, 5],
    "ticker_2": [10, 15, 12, 13],
})
test_annual_return_ratio_df = pd.DataFrame({
    "ticker_1": [2.0, -1.0, 3.0],
    "ticker_2": [0.5, -0.3, 0.1],
})
result_np = get_annual_return_ratio_from_initial(test_stock_price_df).values
np.testing.assert_array_equal(result_np, test_annual_return_ratio_df.values)

In [96]:
annual_return_ratio_df = get_annual_return_ratio_from_initial(annual_stock_price_df)
test_annual_return_ratio_df = get_annual_return_ratio_from_initial(test_annual_stock_price_df)

## Task 2 Simple approach

Let's invest all money in most profitable company but for that we need to calculate $E\xi_i$ first.

We can calculate this value from company annual return ratio and from stock price. Let's do both to make sure that we do everything right.

In [97]:
eps = 1e-7

def get_expectation_ratio_from_return_ratio(ticker_return_ratio_df):
    return ticker_return_ratio_df.mean()

def get_expectation_ratio_from_stock_price(ticker_stock_price_df):
    pct_price_change_df = (ticker_stock_price_df.iloc[-1] / ticker_stock_price_df.iloc[0]) - 1
    return pct_price_change_df / (len(ticker_stock_price_df) - 1)

In [98]:
expectation_ratio_1 = get_expectation_ratio_from_return_ratio(annual_return_ratio_df)
expectation_ratio_2 =  get_expectation_ratio_from_stock_price(annual_stock_price_df)
assert sum(abs(expectation_ratio_1 - expectation_ratio_2)) < eps

Looks like we are ready to implement our greedy approach:

$$ \text{company-to-invest} = \max_i E \xi_i $$

Let's implement this approach having tickers and dates of buying and selling:

In [99]:
def get_expectation_ratio_for_greedy_performance(prices_df):
    return get_expectation_ratio_from_stock_price(prices_df)

def find_ticker_for_greedy_selection(prices_df):
    expectation_df = get_expectation_ratio_from_stock_price(prices_df)
    return expectation_df.idxmax()

In [100]:
aapl_df = download_annual_stock_prices(["AAPL"], start_train_date, end_train_date)
assert 0.8 < get_expectation_ratio_from_stock_price(aapl_df) < 0.9

In [101]:
best_greedy_ticker = find_ticker_for_greedy_selection(annual_stock_price_df)
greedy_ticker_train_performance = get_expectation_ratio_for_greedy_performance(annual_stock_price_df[best_greedy_ticker])
greedy_ticker_test_performance = get_expectation_ratio_for_greedy_performance(test_annual_stock_price_df[best_greedy_ticker])
print(f"\n ticker to invest in greedy approach: {best_greedy_ticker}")
print(f"Train expectation ratio: {greedy_ticker_train_performance}")
print(f"Test expectation ratio: {greedy_ticker_test_performance}")


 ticker to invest in greedy approach: ADS.DE
Train expectation ratio: 0.6672755739493247
Test expectation ratio: -0.2845921467482695


Looks like our greedy method is not very helpful.

## Task 3 Variance

If stock has big variance it means that investor cannot be sure about the future. What is the variance in our case?

Your task is to find $D\xi_i$

In [102]:
def get_variance_from_return_ratio(ticker_return_ratio_df):
    return ticker_return_ratio_df.var(ddof=0)

def get_ticker_variance(prices_df):
    return_ratio = get_annual_return_ratio_from_initial(prices_df)
    return get_variance_from_return_ratio(return_ratio)

In [103]:
aapl_df = download_annual_stock_prices(["AAPL"], start_train_date, end_train_date)
assert 1.9 < get_ticker_variance(aapl_df) < 2.0

Then let's reformulate our task, we will select stock to invest by maximizing the following:

$$\text{company-to-invest} = \max_i \left( \frac{E\xi_i} {\sqrt{ D\xi_i}} \right)$$

In [105]:
def find_ticker_for_max_expectation_divided_by_var(prices_df):
    expectation_df = get_expectation_ratio_from_stock_price(prices_df)
    variance_df = get_ticker_variance(prices_df)
    return expectation_df.div(variance_df.pow(0.5)).idxmax()

In [106]:
best_expectation_var_ticker = find_ticker_for_max_expectation_divided_by_var(annual_stock_price_df)
expectation_var_train_performance = get_expectation_ratio_for_greedy_performance(annual_stock_price_df[best_expectation_var_ticker])
greedy_ticker_test_performance = get_expectation_ratio_for_greedy_performance(test_annual_stock_price_df[best_expectation_var_ticker])

print(f"\n ticker to invest in expectation-variance approach: {best_expectation_var_ticker}")
print(f"Train expectation ratio: {expectation_var_train_performance}")
print(f"Test expectation ratio: {greedy_ticker_test_performance}")


 ticker to invest in expectation-variance approach: DIS
Train expectation ratio: 0.347046133188101
Test expectation ratio: -0.25589815088687423


Still not good...

## Task 4 Linear combination

In investing, there is a golden rule not to put all your eggs in one basket. So why shouldn't Ivan diversify his investments?

Let's define the weight vector $w = (w_1, \ldots, w_n)$ such that $|w| = \sum_{i} w_i = 1;$ and  $ 0 \le w_i \le 1$ .

Our solution can then be represented as:
$\xi = \sum_i w_i \xi_i$

**Task:** Expand the final formula

$$ \max_w \left (  \frac{E[\xi]} { \sqrt{D[\xi]} } \right)   =
    \max_w \left (  \frac{E \left[ \sum_i w_i \xi_i \right] } { \sqrt{D \left[ \sum_i w_i \xi_i \right] } } \right)  = \ldots
$$  



To find best vector $w$ we have to create a function that returns our metric having vector $w$

In [131]:
def get_expectation(prices_df, weights):
    """Calculate expected profit if we invest in each tickers with certain weight."""
    expectation_df = get_expectation_ratio_from_stock_price(prices_df)
    return expectation_df.mul(weights).sum()

def create_functional(priced_df):
    annual_ratio_df: pd.DataFrame = get_annual_return_ratio_from_initial(priced_df)
    
    def wrapper(weights):
        weighted_annual_ratio_sum_df = annual_ratio_df.mul(weights).sum(axis="rows")  # sum(w_i * xi_i)
        weighted_expectation = weighted_annual_ratio_sum_df.mean()
        weighted_variance = weighted_annual_ratio_sum_df.var(ddof=0)
        return weighted_expectation / np.sqrt(weighted_variance)
    return wrapper


functional = create_functional(annual_stock_price_df)

equal_weights = np.array([1 / len(tickers) for _ in tickers])
metric_for_equal_weights = functional(equal_weights)

assert 1.0 < metric_for_equal_weights < 1.5

## Task 5 Optimization

But how to find best weights?

Let's define optimization problem and use _minimize_ function from _sicpy_ package.

**Your task** Find best weights and evaluate train and test results.

In [168]:
from scipy.optimize import minimize

def constraint(x):
    print(x)
    return sum(x) - 1

con = {"type": "eq", "fun": constraint}
minimization_functional = lambda weights: - functional(weights)
result = minimize(minimization_functional, equal_weights, constraints=con)
result

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
[0.10000001 0.1        0.1        0.1        0.1        0.1
 0.1        0.1        0.1        0.1       ]
[0.1        0.10000001 0.1        0.1        0.1        0.1
 0.1        0.1        0.1        0.1       ]
[0.1        0.1        0.10000001 0.1        0.1        0.1
 0.1        0.1        0.1        0.1       ]
[0.1        0.1        0.1        0.10000001 0.1        0.1
 0.1        0.1        0.1        0.1       ]
[0.1        0.1        0.1        0.1        0.10000001 0.1
 0.1        0.1        0.1        0.1       ]
[0.1        0.1        0.1        0.1        0.1        0.10000001
 0.1        0.1        0.1        0.1       ]
[0.1        0.1        0.1        0.1        0.1        0.1
 0.10000001 0.1        0.1        0.1       ]
[0.1        0.1        0.1        0.1        0.1        0.1
 0.1        0.10000001 0.1        0.1       ]
[0.1        0.1    

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: -2.872644938828058
       x: [ 2.342e+02  3.343e+02  2.958e+02 -3.281e+02  4.290e+02
            4.297e+02  6.404e+02  1.342e+03  2.367e+03 -5.743e+03]
     nit: 40
     jac: [ 1.069e-03 -1.126e-04 -9.835e-06  1.115e-04  1.920e-04
           -1.537e-04 -2.012e-04  1.556e-04  1.426e-04  1.056e-04]
    nfev: 475
    njev: 40

In [166]:
result["x"]

array([  234.19514438,   334.29876836,   295.79391889,  -328.10280765,
         428.98722287,   429.72034213,   640.36396546,  1342.31598618,
        2366.55938701, -5743.13192762])

In [158]:
import numpy as np
from scipy.optimize import minimize

# Objective function
def objective(x):
    return 5 + x[0]

# Constraint function
def constraint(x):
    return sum(x) - 1

# Initial guess
x0 = np.array([0.5, 0.5])

# Constraints dictionary
con = {'type': 'eq', 'fun': constraint}

# Perform minimization
result = minimize(objective, x0, constraints=con)

print(result)


 message: Rank-deficient equality constraint subproblem HFTI
 success: False
  status: 7
     fun: -1490116119384767.5
       x: [-1.490e+15  1.490e+15]
     nit: 24
     jac: [ 1.000e+00  0.000e+00]
    nfev: 72
    njev: 24


## Task 6 Bonus: Experiment with initial weights


For running mimimzation algorithm we need to define initial vector $w_0$, but how to do that?

One of the approaches is to try $N$ different starting points and select the best.

**Your task**
1. Implement algorithm that generates $N$ random vectors for weights then tries to minimize functional $N$ times using these vectors as a starting points. And returns the best founded weights.
2. Apply this  algorithm for our task and compare results


In [ ]:
from tqdm import tqdm

def generate_random_weights(vector_size):
    # Write your code here
    pass

def random_search_for_initial_weights(functional_to_mimimize, n_tries, vector_size):
    # Write your code here
    pass


optimal_weights, func_value = random_search_for_initial_weights(minimization_functional, 100, vector_size= len(tickers))


print("Optimal weights:", optimal_weights)
print("Maximized F(weights):", func_value)
print("train expectation:", get_expectation(tickers,start_train_date, end_train_date, optimal_weights))
print("test expectation:", get_expectation(tickers, start_test_date, end_test_date, optimal_weights))