In [ ]:
#!pip install yfinance

# Invest Portfolio

Ivan has a large amout of money, and he starts to think how to invest this money to gain maximum profit.
He chooses 10 candidate companies for that, but since Ivan is new in investing he needs your advice. In this notebook we will help Ivan in his journey.      

In [2]:
# 10 companies to consider, key - ticker name, value -  short description.
tickers = {
    "BA": "The Boeing Company",
    "MCD": "McDonald's Corporation",
    "GOOGL": "Google Company",
    "DIS": "The Walt Disney Company",
    "PFE": "Pfizer Inc.",
    "AMT": "American Tower Corporation",
    "VOD": "Vodafone Group Public Limited Company",
    "BNP.PA": "BNP Paribas Bank",
    "ADS.DE": "Adidas",
    "TM": "Toyota Motor Corporation",
}


## Task 1 Download and preprocess data

We will use data from 2010 till 2021 for training and data from 2021 till 2024  for testing purpose.



In [22]:
start_train_date = "2010-01-01"
end_train_date = "2021-01-01"
start_test_date = "2021-01-01"
end_test_date = "2024-01-01"

Write a function that takes ticker name, start and end dates and returns pandas series of annual stock prices.



In [109]:
import yfinance as yf
import pandas as pd

In [103]:
data = yf.download(list(tickers.keys()), start="2010-01-01", end="2021-01-01", interval="1mo", progress=False)["Open"][::12]
data

Ticker          ADS.DE         AMT          BA     BNP.PA         DIS  \
Date                                                                    
2010-01-01   37.770000   43.490002   55.720001  55.900002   32.500000   
2011-01-01   49.279999   51.910000   66.150002  48.299999   37.740002   
2012-01-01   49.509998   60.450001   74.699997  30.450001   37.970001   
2013-01-01   67.330002   78.389999   76.550003  42.584999   50.799999   
2014-01-01   92.639999   79.510002  136.009995  56.650002   76.040001   
2015-01-01   57.619999   99.160004  131.070007  49.259998   94.910004   
2016-01-01   89.910004   96.290001  141.380005  52.590000  103.120003   
2017-01-01  149.750000  106.730003  156.300003  60.119999  105.300003   
2018-01-01  167.149994  143.160004  295.750000  62.250000  108.949997   
2019-01-01  182.399994  157.110001  316.190002  39.474998  108.099998   
2020-01-01  289.799988  229.679993  328.549988  52.830002  145.289993   

Ticker          GOOGL         MCD        PFE          TM        VOD  
Date                                                                 
2010-01-01  15.689439   62.630001  17.333965   84.750000  23.649338  
2011-01-01  14.926927   77.099998  16.793169   79.019997  26.941896  
2012-01-01  16.339840  101.330002  20.740038   67.389999  28.695210  
2013-01-01  18.003504   89.400002  24.222012   94.779999  26.258919  
2014-01-01  27.914413   96.809998  28.908918  121.599998  39.755352  
2015-01-01  26.629999   94.129997  29.667933  126.230003  34.080002  
2016-01-01  38.110001  117.250000  30.218216  121.519997  32.119999  
2017-01-01  40.030998  121.860001  31.024668  118.169998  24.840000  
2018-01-01  52.651001  173.729996  34.516129  127.430000  32.160000  
2019-01-01  51.360001  175.410004  40.910816  114.680000  19.299999  
2020-01-01  67.420502  198.000000  37.286530  142.000000  19.379999

In [108]:
diff_df = data.diff(1)[1:]
diff_df.div(data.iloc[0])

Ticker        ADS.DE       AMT        BA    BNP.PA       DIS     GOOGL  \
Date                                                                     
2011-01-01  0.304739  0.193608  0.187186 -0.135957  0.161231 -0.048600   
2012-01-01  0.006089  0.196367  0.153446 -0.319320  0.007077  0.090055   
2013-01-01  0.471803  0.412509  0.033202  0.217084  0.394769  0.106037   
2014-01-01  0.670108  0.025753  1.067121  0.251610  0.776615  0.631693   
2015-01-01 -0.927191  0.451828 -0.088657 -0.132200  0.580615 -0.081865   
2016-01-01  0.854911 -0.065992  0.185032  0.059571  0.252615  0.731702   
2017-01-01  1.584326  0.240055  0.267767  0.134705  0.067077  0.122439   
2018-01-01  0.460683  0.837664  2.502692  0.038104  0.112308  0.804363   
2019-01-01  0.403760  0.320763  0.366834 -0.407424 -0.026154 -0.082285   
2020-01-01  2.843526  1.668659  0.221823  0.238909  1.144308  1.023650   

Ticker           MCD       PFE        TM       VOD  
Date                                                
2011-01-01  0.231039 -0.031199 -0.067611  0.139224  
2012-01-01  0.386875  0.227696 -0.137227  0.074138  
2013-01-01 -0.190484  0.200876  0.323186 -0.103017  
2014-01-01  0.118314  0.270389  0.316460  0.570690  
2015-01-01 -0.042791  0.043788  0.054631 -0.239979  
2016-01-01  0.369152  0.031746 -0.055575 -0.082878  
2017-01-01  0.073607  0.046524 -0.039528 -0.307831  
2018-01-01  0.828197  0.201423  0.109263  0.309522  
2019-01-01  0.026824  0.368911 -0.150442 -0.543778  
2020-01-01  0.360690 -0.209086  0.322360  0.003383

In [112]:
test_df = pd.DataFrame({
    "ticker_1": [1, 3, 2, 5],
    "ticker_2": [10, 15, 12, 13],
})

test_diff_df = test_df.diff(1)[1:]
test_diff_df.div(test_df.iloc[0])

ticker_1  ticker_2
1       2.0       0.5
2      -1.0      -0.3
3       3.0       0.1

In [83]:
import yfinance as yf

import numpy as np


def download_annual_stock_price(ticker, buy_date="2010-01-01", sell_date="2021-01-01"):
    """Download the annual stock price using yf.download"""
    data = yf.download(ticker, start=buy_date, end=sell_date, interval="1mo", progress=False)[::12]
    return data["Open"].values


annual_stock_price = {
    ticker: download_annual_stock_price(ticker, start_train_date, end_train_date)
    for ticker in tickers
}
annual_stock_price["BNP.PA"]

array([55.90000153, 48.29999924, 30.45000076, 42.58499908, 56.65000153,
       49.25999832, 52.59000015, 60.11999893, 62.25      , 39.47499847,
       52.83000183])

In [84]:
download_annual_stock_price(["AAPL"], "2010-01-01", end_train_date)

array([ 7.62249994, 11.63000011, 14.62142944, 19.77928543, 19.84571457,
       27.84749985, 25.65250015, 28.95000076, 42.54000092, 38.72249985,
       74.05999756])


Let's define $\xi_i$ as random variable equals annual return ratio of the $\text{stock}_i$  relative to the buying price.

Convert annual stock price to annual return ratio considering that we've bought stock at moment $t=0$.
i.e. if the annoaul stock prices are $(10, 15, 12, 13)$,
 annual return ratio will be $(0.5, -0.3, 0.1)$

In [85]:
def get_annual_return_ratio_from_initial(annual_stock_prices):
    annual_ratio = (annual_stock_prices[1:] - annual_stock_prices[:-1]) / annual_stock_prices[0]
    return annual_ratio


test_annual_return_ratio = get_annual_return_ratio_from_initial(np.array([1, 3, 2]))
assert np.all(test_annual_return_ratio == np.array([2.0, -1.0]))

test_annual_return_ratio = get_annual_return_ratio_from_initial(np.array([10, 15, 12, 13]))
assert np.all(test_annual_return_ratio == np.array([0.5, -0.3, 0.1]))

annual_return_ratio = {
    ticker: get_annual_return_ratio_from_initial(values)
    for ticker, values in annual_stock_price.items()
}

## Task 2 Simple approach

Let's invest all money in most profitable company but for that we need to calculate $E\xi_i$ first.

We can calculate this value from company annual return ratio and from stock price. Let's do both to make sure that we do everything right.

In [86]:
eps = 1e-7


def get_expectation_ratio_from_return_ratio(ticker_return_ratio):
    return np.mean(ticker_return_ratio)


def get_expectation_ratio_from_stock_price(ticker_stock_price):
    pct_price_change = (ticker_stock_price[-1] / ticker_stock_price[0]) - 1
    return pct_price_change / (len(ticker_stock_price) - 1)


for ticker in tickers:
    expectation_ratio_1 = get_expectation_ratio_from_return_ratio(annual_return_ratio[ticker])
    expectation_ratio_2 = get_expectation_ratio_from_stock_price(annual_stock_price[ticker])
    assert abs(expectation_ratio_1 - expectation_ratio_2) < eps


Looks like we are ready to implement our greedy approach:

$$ \text{company-to-invest} = \max_i E \xi_i $$

Let's implement this approach having tickers and dates of buying and selling:

In [87]:
def get_expectation_ratio_for_greedy_performance(ticker, buy_date, sell_date):
    ticker_prices = download_annual_stock_price(ticker, buy_date, sell_date)
    return get_expectation_ratio_from_stock_price(ticker_prices)


def find_ticker_for_greedy_selection(tickers, buy_date, sell_date):
    max_expectation_ration = -float("INF")
    company_to_invest = ""
    for ticker in tickers:
        expectation_ratio = get_expectation_ratio_for_greedy_performance(ticker, buy_date, sell_date)
        if expectation_ratio > max_expectation_ration:
            max_expectation_ration = expectation_ratio
            company_to_invest = ticker
    return company_to_invest


assert 0.8 < get_expectation_ratio_for_greedy_performance("AAPL", start_train_date, end_train_date) < 0.9

In [88]:
best_greedy_ticker = find_ticker_for_greedy_selection(tickers, start_train_date, end_train_date)
greedy_ticker_train_performance = get_expectation_ratio_for_greedy_performance(
    best_greedy_ticker, start_train_date, end_train_date
)
greedy_ticker_test_performance = get_expectation_ratio_for_greedy_performance(
    best_greedy_ticker, start_test_date, end_test_date
)
print(f"\n ticker to invest in greedy approach: {best_greedy_ticker}")
print(f"Train expectation ratio: {greedy_ticker_train_performance}")
print(f"Test expectation ratio: {greedy_ticker_test_performance}")



 ticker to invest in greedy approach: ADS.DE
Train expectation ratio: 0.6672755739493247
Test expectation ratio: -0.2845921467482695


Looks like our greedy method is not very helpful.

## Task 3 Variance

If stock has big variance it means that investor cannot be sure about the future. What is the variance in our case?

Your task is to find $D\xi_i$

In [89]:
def get_variance_from_return_ratio(ticker_return_ratio):
    return np.var(ticker_return_ratio, ddof=0)


def get_ticker_variance(ticker, buy_date, sell_date):
    ticker_prices = download_annual_stock_price(ticker, buy_date, sell_date)
    return_ratio = get_annual_return_ratio_from_initial(ticker_prices)
    return get_variance_from_return_ratio(return_ratio)


assert 1.9 < get_ticker_variance("AAPL", start_train_date, end_train_date) < 2.0

Then let's reformulate our task, we will select stock to invest by maximizing the following:

$$\text{company-to-invest} = \max_i \left( \frac{E\xi_i} {\sqrt{ D\xi_i}} \right)$$

In [90]:
def find_ticker_for_max_expectation_divided_by_var(tickers, buy_date, sell_date):
    max_expect_div_by_var = -float("INF")
    company_to_invest = ""
    for ticker in tickers:
        expectation_ratio = get_expectation_ratio_for_greedy_performance(ticker, buy_date, sell_date)
        var = get_ticker_variance(ticker, buy_date, sell_date)
        expect_div_by_var = expectation_ratio / np.sqrt(var)
        if expect_div_by_var > max_expect_div_by_var:
            max_expect_div_by_var = expect_div_by_var
            company_to_invest = ticker
    return company_to_invest

In [91]:
best_expectation_var_ticker = find_ticker_for_max_expectation_divided_by_var(
    tickers, start_train_date, end_train_date
)
expectation_var_train_performance = get_expectation_ratio_for_greedy_performance(
    best_expectation_var_ticker, start_train_date, end_train_date
)
greedy_ticker_test_performance = get_expectation_ratio_for_greedy_performance(
    best_expectation_var_ticker, start_test_date, end_test_date
)
print(f"\n ticker to invest in expectation-variance approach: {best_expectation_var_ticker}")
print(f"Train expectation ratio: {expectation_var_train_performance}")
print(f"Test expectation ratio: {greedy_ticker_test_performance}")



 ticker to invest in expectation-variance approach: DIS
Train expectation ratio: 0.347046133188101
Test expectation ratio: -0.25589815088687423


Still not good...

## Task 4 Linear combination

In investing, there is a golden rule not to put all your eggs in one basket. So why shouldn't Ivan diversify his investments?

Let's define the weight vector $w = (w_1, \ldots, w_n)$ such that $|w| = \sum_{i} w_i = 1;$ and  $ 0 \le w_i \le 1$ .

Our solution can then be represented as:
$\xi = \sum_i w_i \xi_i$

**Task:** Expand the final formula

$$ \max_w \left (  \frac{E[\xi]} { \sqrt{D[\xi]} } \right)   =
    \max_w \left (  \frac{E \left[ \sum_i w_i \xi_i \right] } { \sqrt{D \left[ \sum_i w_i \xi_i \right] } } \right)  = \ldots
$$  



To find best vector $w$ we have to create a function that returns our metric having vector $w$

In [ ]:
# ``var = mean(x)``, where ``x = abs(a - a.mean())**2``.

In [69]:
cov_arr = np.array([])
for i in range(1, 7):
    for j in range(1, 7):
        cov_arr = np.append(cov_arr, i * max(i, j))

array([3, 8, 0])

In [4]:
arr_1 = np.array([])
arr_2 = np.array([])
for i in range(1, 7):
    for j in range(1, 7):
        arr_1 = np.append(arr_1, i)
        arr_2 = np.append(arr_2, max(i, j))

array([1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.,
       3., 4., 4., 4., 4., 4., 4., 5., 5., 5., 5., 5., 5., 6., 6., 6., 6.,
       6., 6.])

In [61]:
0.4 * arr_1.mean() + 0.6 * arr_2.mean()

4.083333333333333

In [62]:
(0.4 * arr_1 + 0.6 * arr_2).mean()

4.083333333333333

In [74]:
(arr_1 * arr_2).mean() - arr_1.mean() * arr_2.mean()

1.4583333333333321

1.4583333333333333

In [37]:

x1 = np.array([1, 2, 3, 4, 5, 6])
x2 = np.array([1, 2, 3, 4, 5, 6])
x3 = x1 + x2

print(np.var(x1) * 4)
print(np.var(x3))
print(np.var(x1) + np.var(x2) + 2 * (np.mean(x1 ** 2) - np.mean(x2) ** 2))
print(np.var(x1) + np.var(x2) + 2 * (np.mean((x1 - np.mean(x1)) * (x2 - np.mean(x2)))))
print(np.var(x1) + np.var(x2) + 2 * np.cov(x1, x2, ddof=0)[0, 1])

11.666666666666666
11.666666666666666
11.666666666666664
11.666666666666666
11.666666666666666


In [1]:
annual_stock_price = {
    ticker: download_annual_stock_price(ticker, start_train_date, end_train_date)
    for ticker in tickers
}
annual_return_ratio = {
    ticker: get_annual_return_ratio_from_initial(values)
    for ticker, values in annual_stock_price.items()
}

NameError: name 'tickers' is not defined

In [100]:
def get_expectation(tickers, buy_date, sell_date, weights):
    """Calculate expected profit if we invest in each tickers with certain weight."""
    # pct_profit = 0
    # for ticker, w in zip(tickers, weights):
    #     annual_ratios = annual_return_ratio[ticker]
    ...

def get_weighted_annual_ratios(annual_return_ratios, weights):
    weighted_annual_ratios = None
    for annual_ratios, w in zip(annual_return_ratios, weights):
        if weighted_annual_ratios is None:
            weighted_annual_ratios = np.zeros_like(annual_ratios)
        weighted_annual_ratios += w * annual_ratios
    return weighted_annual_ratios


def create_functional(tickers, buy_date, sell_date):
    annual_stock_price = {
        ticker: download_annual_stock_price(ticker, buy_date, sell_date) 
        for ticker in tickers
    }
    annual_return_ratio = {
        ticker: get_annual_return_ratio_from_initial(values) 
        for ticker, values in annual_stock_price.items()
    }

    def functional(weights):
        print(weights)
        annual_ratios = get_weighted_annual_ratios(annual_return_ratio.values(), weights)
        expectation = annual_ratios.mean()
        variance = annual_ratios.var()
        return expectation / np.sqrt(variance)

    return functional


functional = create_functional(tickers, start_train_date, end_train_date)

equal_weights = [1 / len(ticker) for ticker in tickers]
print([ticker for ticker in tickers])
metric_for_equal_weights = functional(equal_weights)

assert 1.0 < metric_for_equal_weights < 1.5


['BA', 'MCD', 'GOOGL', 'DIS', 'PFE', 'AMT', 'VOD', 'BNP.PA', 'ADS.DE', 'TM']
[0.5, 0.3333333333333333, 0.2, 0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.16666666666666666, 0.16666666666666666, 0.5]


## Task 5 Optimization

But how to find best weights?

Let's define optimization problem and use _minimize_ function from _sicpy_ package.

**Your task** Find best weights and evaluate train and test results.

In [97]:
from scipy.optimize import minimize

minimization_functional = lambda weights: - functional(weights)

minimize(minimization_functional, 11)


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: -0.6686818524136674
        x: [ 1.100e+01]
      nit: 0
      jac: [-7.451e-09]
 hess_inv: [[1]]
     nfev: 2
     njev: 1

## Task 6 Bonus: Experiment with initial weights


For running mimimzation algorithm we need to define initial vector $w_0$, but how to do that?

One of the approaches is to try $N$ different starting points and select the best.

**Your task**
1. Implement algorithm that generates $N$ random vectors for weights then tries to minimize functional $N$ times using these vectors as a starting points. And returns the best founded weights.
2. Apply this  algorithm for our task and compare results


In [ ]:
from tqdm import tqdm


def generate_random_weights(vector_size):
    # Write your code here
    pass


def random_search_for_initial_weights(functional_to_minimize, n_tries, vector_size):
    # Write your code here
    pass


optimal_weights, func_value = random_search_for_initial_weights(minimization_functional, 100, vector_size=len(tickers))

print("Optimal weights:", optimal_weights)
print("Maximized F(weights):", func_value)
print("train expectation:", get_expectation(tickers, start_train_date, end_train_date, optimal_weights))
print("test expectation:", get_expectation(tickers, start_test_date, end_test_date, optimal_weights))